/**
 * Generated by scripts/build_photos.py from the .jpg originals in this folder.
 * Do not edit by hand: re-run the script after replacing a photograph.
 *
 * Each entry carries the shipped .webp, its real dimensions so a frame can
 * reserve its height before the file arrives, the focal point every crop keeps
 * in view, and `lqip`: a 20px blurred thumbnail of the same photograph, inlined
 * so the frame is the right colours on the first paint.
 *
 * `credit` is not shown on screen. The Unsplash licence does not require
 * attribution, but who took a photograph is worth keeping with the file, and
 * CREDITS.md in this folder is the readable copy.
 */
import companiesMeetingSrc from './companies-meeting.webp'
import colleaguesSrc from './colleagues.webp'

export interface PhotoAsset {
  src: string
  width: number
  height: number
  alt: string
  /** object-position, so a cropped frame keeps the subject rather than the ceiling. */
  focal: string
  lqip: string
  credit: { name: string; url: string }
}

export const photos = {
  companiesMeeting: {
    src: companiesMeetingSrc,
    width: 2000,
    height: 1335,
    alt: "Four colleagues around a meeting table with laptops open, mid-discussion",
    focal: "50% 42%",
    credit: { name: "Christina @ wocintechchat.com", url: "https://unsplash.com/@wocintechchat" },
    lqip:
      "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoUAA0APsFOoEqnpCMhsAgA8BgJQBOmUABflS0HryLbRV6aoAD+2BfMujLxImgQC3hOgzIrtXwEGOX91m58OJO4vX8j1CiXfbkfTwOGnyeCg0cCwezfdq2rS6pgwxUg9TX2+j8btwJ3j01kKH9DWLmE5uqUq6lFeKZhJPcQ72TQECklEFb9AAAA",
  },
  colleagues: {
    src: colleaguesSrc,
    width: 1600,
    height: 1200,
    alt: "Five young people sitting together on red steps outdoors with laptops open, one of them taking a photograph of the group",
    focal: "50% 45%",
    credit: { name: "Iwaria Inc.", url: "https://unsplash.com/@iwaria" },
    lqip:
      "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAQBACdASoUAA8APsFOoUqnpCMhsAgA8BgJYgCw7BerLefNXWOJwdxkAAD+63luf8S8IpwG/metkq+vG3jBgtIemXkR+b5SL1yN7D7eCMUTXh8pUKy69NminJ0GgPUF3AifQF59nRuiZk5C9aA5LxeSFDQ/N2CjDEJfFutsmucQAUz8lfafCy9VMSq/ROZFFBNRzK2R7ZaAAA==",
  },
} satisfies Record<string, PhotoAsset>
