"""Turns the downloaded photographs into the assets the app ships.

For each source .jpg in frontend/src/assets/photos it writes a .webp at a
sensible display width, measures it, and builds a 20px-wide blurred thumbnail
inlined as a data URI. The numbers and the thumbnail go into manifest.ts, which
is what the Photo component reads.

Run: python3 build_photos.py <repo>/frontend/src/assets/photos
"""

import base64
import io
import json
import sys
from pathlib import Path

from PIL import Image, ImageFilter

# name -> (max width shipped, alt text, object-position focal point, credit)
PLAN = {
    "companies-meeting": (
        2000,
        "Four colleagues around a meeting table with laptops open, mid-discussion",
        "50% 42%",
        ("Christina @ wocintechchat.com", "https://unsplash.com/@wocintechchat"),
    ),
    "colleagues": (
        1600,
        "Five young people sitting together on red steps outdoors with laptops open, "
        "one of them taking a photograph of the group",
        "50% 45%",
        ("Iwaria Inc.", "https://unsplash.com/@iwaria"),
    ),
}


def lqip(img: Image.Image) -> str:
    """A 20px-wide blurred thumbnail, small enough to inline."""
    w = 20
    h = max(1, round(img.height * w / img.width))
    thumb = img.resize((w, h), Image.LANCZOS).filter(ImageFilter.GaussianBlur(0.6))
    buf = io.BytesIO()
    thumb.save(buf, "WEBP", quality=55)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode()


def main(folder: Path) -> None:
    entries = []
    for name, (max_w, alt, focal, credit) in PLAN.items():
        src = next((folder / f"{name}{ext}" for ext in (".jpg", ".jpeg", ".png", ".webp")
                    if (folder / f"{name}{ext}").exists()), None)
        if src is None:
            print(f"skip {name}: no source file")
            continue

        img = Image.open(src).convert("RGB")
        if img.width > max_w:
            img = img.resize((max_w, round(img.height * max_w / img.width)), Image.LANCZOS)

        out = folder / f"{name}.webp"
        img.save(out, "WEBP", quality=78, method=6)
        entries.append(
            {
                "key": name,
                "file": out.name,
                "width": img.width,
                "height": img.height,
                "alt": alt,
                "focal": focal,
                "lqip": lqip(img),
                "credit": {"name": credit[0], "url": credit[1]},
            }
        )
        print(f"{name}: {img.width}x{img.height}, {out.stat().st_size // 1024} kB")

    ident = {"companies-meeting": "companiesMeeting", "colleagues": "colleagues"}
    imports = "\n".join(f"import {ident[e['key']]}Src from './{e['file']}'" for e in entries)
    bodies = []
    for e in entries:
        bodies.append(
            f"  {ident[e['key']]}: {{\n"
            f"    src: {ident[e['key']]}Src,\n"
            f"    width: {e['width']},\n"
            f"    height: {e['height']},\n"
            f"    alt: {json.dumps(e['alt'])},\n"
            f"    focal: {json.dumps(e['focal'])},\n"
            f"    credit: {{ name: {json.dumps(e['credit']['name'])}, "
            f"url: {json.dumps(e['credit']['url'])} }},\n"
            f"    lqip:\n      {json.dumps(e['lqip'])},\n"
            f"  }},"
        )

    manifest = f"""/**
 * Generated by scripts/build_photos.py from the .jpg originals in this folder.
 * Do not edit by hand: re-run the script after replacing a photograph.
 *
 * Each entry carries the shipped .webp, its real dimensions so a frame can
 * reserve its height before the file arrives, the focal point every crop keeps
 * in view, and `lqip`: a 20px blurred thumbnail of the same photograph, inlined
 * so the frame is the right colours on the first paint.
 *
 * `credit` is not shown on screen. The Unsplash licence does not require
 * attribution, but who took a photograph is worth keeping with the file, and
 * CREDITS.md in this folder is the readable copy.
 */
{imports}

export interface PhotoAsset {{
  src: string
  width: number
  height: number
  alt: string
  /** object-position, so a cropped frame keeps the subject rather than the ceiling. */
  focal: string
  lqip: string
  credit: {{ name: string; url: string }}
}}

export const photos = {{
{chr(10).join(bodies)}
}} satisfies Record<string, PhotoAsset>
"""
    (folder / "manifest.ts").write_text(manifest, encoding="utf-8")

    credits = ["# Photographs", "",
               "All three are Unsplash, free to use under the Unsplash licence, which asks",
               "for no attribution. Recorded here anyway so the source of each file is",
               "known without opening it.", ""]
    for e in entries:
        credits.append(f"- `{e['file']}` — {e['credit']['name']}, {e['credit']['url']}")
    credits += ["",
                "To replace one: drop a new .jpg over the original here, keeping the name,",
                "then re-run `python3 scripts/build_photos.py frontend/src/assets/photos`,",
                "which rewrites the .webp, the dimensions and the blurred thumbnail."]
    (folder / "CREDITS.md").write_text("\n".join(credits) + "\n", encoding="utf-8")
    print("wrote manifest.ts and CREDITS.md")


if __name__ == "__main__":
    main(Path(sys.argv[1]))
